---
- name: Install package
  hosts: web
  vars:
    source_path: /work_dir/training-files
    apache_dst_path: /etc/apache2/apache2.conf
    php_dst_path: /var/www/html/index.html
  gather_facts: no
  tasks:
  - name: Install apache Package
    become: yes
    yum:
      name: apache2
      state: latest
  - name: Copy apache configuration file
    become: yes
    copy:
      src: "{{ source_path }}/apache2.conf"
      dest: "{{ apache_dst_path }}"
  - name: Copy index.html file
    become: yes
    copy:
      src: "{{ source_path }}/index.html"
      dest: "{{ php_dst_path }}"
  - name: Start apache2 service
    become: yes
    service:
      name: apache2
      state: started
      enabled: yes